# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
           java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Deploy to Github Package Registry
        env:
          TOKEN: ${{ secrets.TOKEN }}
          run: |
            mkdir -p ~/.m2
            echo "<settings><servers><server><id>gh</id><username>$(echo "$GITHUB_REPOSITORY" | 
            awk -F / '{print 
            $1}')</username><password>\${env.TOKEN}</password></server></servers></settings>" > 
            ~/.m2/settings.xml
            REPO="gh::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}"
            mvn deploy -DaltReleaseDeploymentRepository="${REPO}" -
            DaltSnapshotDeploymentRepository="${REPO}"
